### PR TITLE
Addition to RAM Writes.

### PR DESCRIPTION
**Pull request by Korozin**
Added a new Anti-Kick, which has the benefits of the Anti-Kick from PureClient v1.6

Added See hitbox through walls. Which draws the hitbox and allows you to see them through any block, without any graphical glitches.

### CODE REVIEW

**Comment by Korozin** [comment]
Added a cracked version of Katope's K-Aura code.

**Comment by Korozin** [comment]
Added a code-plugin named MICV which allows for the manipulation of the Mic. See [README](https://github.com/Korozin/MinecraftWiiUPlaza/blob/main/Codes/Execute-ASM/MICV/README.md) for explanation.

**Comment by Korozin** [comment]
Added Easy Hit Arrow

**Comment by Korozin** [comment]
Added an item spammer.

**Comment by Korozin** [comment]
Added a .elf client (I think, lol)

**Comment by Korozin** [comment]
Added the compiled .elf of the ShineClient which supports all regions.

**Comment by MinecraftWiiUCodes** [comment]
Sorry for being dead for 100 years lol

**Comment by Korozin** [comment]
Oh it's fine, dw lmao

**Pull request merged**
