### PR TITLE
Add more code content.

### PR DESCRIPTION
**Pull request by Korozin**
Skailed was kind enough to provide some interesting codes created by an individual named Inupong.  

I've also added the AuroraClient source.

### CODE REVIEW

**Comment by cedkeChat** [comment]
imagine add catyclient x)

**Comment by ghost** [comment]
> imagine add catyclient x)

You can add it if you want. I don't think I have the files for it anymore.

**Comment by 00cedke** [comment]
bah je voudrais bien mais j'ai protéger mes serveurs webs

**Comment by ghost** [comment]
> bah je voudrais bien mais j'ai protéger mes serveurs webs

No one said you have to link it to your servers. You can just upload the source.

All it is, is ShineClient but with an ELF forwarder, correct? No harm in uploading that to show other people how to do it.

**Comment by 00cedke** [comment]
wdym, i'm new for create client bro but i try to draw my menu with
CustomSkySource and q-client lib because i have q-client lib

**Comment by ghost** [comment]
Ah, I thought you were talking about the other one you made with ShineClient as a base.

**Comment by 00cedke** [comment]
yes because I am new in this field, since then I have recovered the q-client library and some code belonging to q-client which will allow me to make my own mod menu

**Pull request closed without merging**
