### PR TITLE
Added ShineClient

### PR DESCRIPTION
**Pull request by Korozin**

### CODE REVIEW

**Comment by Toffelzz** [comment]
don't work, just a useless client that show ur wiiu ip adress. useless + bullshit + have screen

**Comment by Korozin** [comment]
> don't work, just a useless client that show ur wiiu ip adress. useless + bullshit + have screen

Incorrect, it just checks for the Japanese Title ID specifically. Maybe back up your claims before you decide to all a tool useless

**Comment by Korozin** [comment]
> don't work, just a useless client that show ur wiiu ip adress. useless + bullshit + have screen

Also idk why you think it doesnt work? After using it myself it shows the menu with mods, you can turn on and off by selecting with A, in addition to that it also has TCP Gecko running ontop of it so you arent confined to just the mods that the client offers.

**Comment by Korozin** [comment]
> > > don't work, just a useless client that show ur wiiu ip adress. useless + bullshit + have screen
> > 
> > 
> > Incorrect, it just checks for the Japanese Title ID specifically. Maybe back up your claims before you decide to all a tool useless
> 
> and how are we supposed to know? Perhaps we should add details and explanations on how the mod works? Who is the creator of this client?

To be fair it should be quite self-explanatory, it's an ELF file, you load it in Homebrew like all Wii U ELF files, it launches the game then even says onscreen how to open the menu. Also the creator of the client is Clover.

**Comment by Korozin** [comment]
Added Shine's Source Code and a Python script which sends the Client via TCPGecko.

**Pull request merged**
