### PR TITLE
Added MineMods v3

### PR DESCRIPTION
**Pull request by Pop-Apple**
## MineMods 
**Developing by Famigb**

MineMods-1 MineMods-2

### CODE REVIEW

**Comment by MinecraftWiiUCodes** [comment]
I remember a while ago I was looking into the disassembly of MineMods and found some sort of "trojan" in it, so I don't fully trust it.

**Comment by Pop-Apple** [comment]
I'm sorry about that. 🙏  
Close this Pull Request

**Comment by MinecraftWiiUCodes** [comment]
No worries, thanks for wanting to contribute :)

**Comment by Pop-Apple** [comment]
I'll leave it "open" just in case.

**Pull request closed without merging**
